<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    /**
     * INVOICE ATTRIBUTES
     * $this->attributes['id'] - int - ID of the invoice.
     * $this->attributes['date'] - string - Date of the transaction. Different from the timestamps.
     * $this->attributes['invoice_lines'] - array - Array of associated Invoice Lines.
     * $this->attributes['custom_user_id'] - int - ID of the user that made the transaction.
     * $this->attributes['office_id'] - int - ID of the office that handles this transaction.
     * $this->attributes['created_at'] - string - Generated by timestamps(). When this record was added to the db.
     * $this->attributes['updated_at'] - string - Genereated by timestamps(). When this record was last modified in the db.
     */

    // Make Eloquent handle this column as an array.
    protected $casts = [
        'invoice_lines' => 'array',
    ];

    // Determine which fields can be filled in.
    protected $fillable = ['date', 'invoice_lines'/* , 'custom_user_id', 'office_id' */];

    // Getters and setters
    public function getId(): int
    {
        return $this->attributes['id'];
    }

    public function getDate(): string
    {
        return $this->attributes['date'];
    }

    public function setDate(string $date): void
    {
        $this->attributes['date'] = $date;
    }

    public function getInvoiceLines(): array
    {
        return $this->attributes['invoice_lines'];
    }

    public function setInvoiceLines(string $invoiceLines): void
    {
        $this->attributes['invoice_lines'] = $invoiceLines;
    }

    /*public function getCustomUser(): int
    {
        return $this->attributes['custom_user_id'];
    }

    public function setCustomUser(int $customUserId): void
    {
        $this->attributes['custom_user_id'] = $customUserId;
    }

    public function getOffice(): int
    {
        return $this->attributes['office_id'];
    }

    public function setOffice(int $officeId): void
    {
        $this->attributes['office_id'] = $officeId;
    }*/
}
