<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class InvoiceLine extends Model
{
    /**
     * INVOICE LINE ATTRIBUTES
     * $this->attributes['id'] - int - ID of the invoice line.
     * $this->attributes['unit_price'] - float - Price of the individual item.
     * $this->attributes['discount'] - float - Discount that is applied to the price.
     * $this->attributes['quantity'] - int - Amount purchased of the individual item.
     * $this->attributes['reason'] - string - Reason of the invoice line.
     * $this->attributes['invoice_id'] - int - ID of the associated invoice.
     * $this->attributes['phone_id'] - int - ID of the individual item.
     * $this->attributes['created_at'] - string - Generated by timestamps(). When this record was added to the db.
     * $this->attributes['updated_at'] - string - Generated by timestamps(). When this record was last modified in the db.
     */

    // Determine which fields can be filled in.
    protected $fillable = ['unit_price', 'discount', 'quantity', 'reason', 'invoice_id'/* , 'phone_id' */];

    // Getters and setters
    public function getId(): int
    {
        return $this->attributes['id'];
    }

    public function getUnitPrice(): float
    {
        return $this->attributes['unit_price'];
    }

    public function setUnitPrice(float $unitPrice): void
    {
        $this->attributes['unit_price'] = $unitPrice;
    }

    public function getDiscount(): float
    {
        return $this->attributes['discount'];
    }

    public function setDiscount(float $discount): void
    {
        $this->attributes['discount'] = $discount;
    }

    public function getQuantity(): int
    {
        return $this->attributes['quantity'];
    }

    public function setQuantity(int $quantity): void
    {
        $this->attributes['quantity'] = $quantity;
    }

    public function getReason(): string
    {
        return $this->attributes['reason'];
    }

    public function setReason(string $reason): void
    {
        $this->attributes['reason'] = $reason;
    }

    public function getInvoiceId(): int
    {
        return $this->attributes['invoice_id'];
    }

    public function setInvoiceId(int $invoiceId): void
    {
        $this->attributes['invoice_id'] = $invoiceId;
    }

    /*public function getPhoneId(): int
    {
        return $this->attributes['phone_id'];
    }

    public function setPhoneId(int $phoneId): void
    {
        $this->attributes['phone_id'] = $phoneId;
    }*/
}
